In [1]:
import numpy as np
array1=(range(30))
array2=([2,3,5])
np.savez("array.npz",array1,array2)

In [2]:
load_array=np.load("array.npz")
array3=np.array([[4,5,6],[1,2,3]])
np.savez("multi_array.npz",load_array["arr_0"],load_array["arr_1"],array3)
npzfile=np.load("multi_array.npz")
print(npzfile["arr_0"])
print(npzfile["arr_1"])
print(npzfile["arr_2"])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
