In [18]:
import numpy as np
array1=np.array([[10,8],[3,5]])
array2=np.linalg.inv(array1)
print(array1@array2)

[[1. 0.]
 [0. 1.]]


In [21]:
w,v=np.linalg.eig(array1)
print("特徵值:",w)
print("特徵向量:",v)

特徵值: [13.  2.]
特徵向量: [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [22]:
u,s,vh,=np.linalg.svd(array1)
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [23]:
s

array([13.94721714,  1.86417116])

In [24]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])