In [1]:
import numpy as np
array1=np.array([[10,8],[3,5]])
array2=np.linalg.inv(array1)
print(array1@array2)

[[1. 0.]
 [0. 1.]]


In [2]:
w,v=np.linalg.eig(array1)
print("特徵值:",w)
print("特徵向量:",v)

特徵值: [13.  2.]
特徵向量: [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [3]:
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))